server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/adm_videos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
      auto-commit: false
      connection-timeout: 20000
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.generate_statistics: false
      hibernate.connection.provider_disables_autocommit: true

  flyway:
    enabled: true
    url: jdbc:mysql://127.0.0.1:3306/adm_videos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: root
    password: 123456
    locations: classpath:db/migration
    baseline-on-migrate: true
    driver-class-name: com.mysql.cj.jdbc.Driver

