version: '3.7'

services:
  mysql:
    container_name: adm_videos_mysql
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASS}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adm_videos_network

networks:
  adm_videos_network: